### ISSUE TITLE
Module 'xmlschema' missing

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#100]
The robotframework core `atest` execution requires Python module `xmlschema`, that is currently missing.

**Comment by test-fullautomation** [comment]
Hi Nguyen,
please add this library.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please look into this.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

`xmlschema` module is only required for atest execution.
So, do we need to add it for only test job (update both build pipelines OSS and BIOS) or add it as required Python module for whole Robot Framework AIO package (the installers).

From my point of view, we should adapted build pipeline to install requirements for atest instead of adding into installer.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

asked other way round: Do we have any negative impact when adding the module also to the installer?

Another aspect is the requirement: In case of it's required that everyone shall be able to execute a full self test of the installed RobotFramework AIO on his own computer, then it is required to have the module available as part of the installation.

**Comment by ngoan1608** [comment]
Hi Holger,

There is no negative impact, only the dependency is added for our AIO package.
You are right! Add it in the installers is much easier for us (just an addition in requirements file for our installer instead of adapting for both build pipelines).

I have also concerned about this module at the first time I run atest for `robotframework`.
This module is required for atest execution butit is not added as dependency of `robotframework`.
They define it in `requirements-run.txt` file and mentioned about it only in README file under atest folder for users (developers) who really need to run the atest they should install the requirements file.

So, I think it is good practice to avoid too many dependencies (in case more module is added for `atest`) for our package.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
xmlschema can be part of the RobotFramework AIO delivery.
It's likely that RobotFramework AIO users want to process xml data. 

This brings me to a simialr point which we discussed already:
We should have in our documentation a generated list of python modules + version which we integrate.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
This ticket has been solved with merged PR #102

**Comment by test-fullautomation** [comment]
solved and already merge with #102
