### ISSUE TITLE
Wrong version number in console

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#123]
I installed setup_RobotFramework_AIO_OSD5Linux_0.8.1.1.deb.

After this I installed RobotFramework_AIO_0.8.1.3-0_amd64.deb (from https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5219911236)

But I forgot to uninstall the previous version 0.8.1.1

During installation of 0.8.1.3-0 the console tells:

`Unpacking robotframework-aio (0.8.1.3) over (0.8.0.0) ...`

But from where did the installer get the information about version 0.8.0.0? I would expect:

`Unpacking robotframework-aio (0.8.1.3) over (0.8.1.1) ...`

**Comment by ngoan1608** [comment]
Hi Holger,

The version information which you are concerning is get from the [control](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/config/build/dpkg_build/control) file.
With version [0.8.1.1](https://github.com/test-fullautomation/RobotFramework_AIO/blob/rel/aio/0.8.1.1/config/build/dpkg_build/control) (and previous versions), version information in control file is not updated properly.
That is the reason why you observed `0.8.0.0` instead of `0.8.1.1`.

That version information is updated properly in current versions:
- [0.8.1.2](https://github.com/test-fullautomation/RobotFramework_AIO/blob/rel/aio/0.8.1.2/config/build/dpkg_build/control)
- [0.8.1.3](https://github.com/test-fullautomation/RobotFramework_AIO/blob/rel/aio/0.8.1.3/config/build/dpkg_build/control)

Currently, this information is updated manually by Thomas and it should be updated for each release tag. So, Thomas has already raised a ticket to update this file automatically with build pipeline [here](https://github.com/test-fullautomation/RobotFramework_AIO/issues/118).

As soon as that feature is implemented, the mismatched version as your observation will be solved because that version information will be same as release tag.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
duplicate to #118
