### ISSUE TITLE
Missing environment variable

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#127]
In case of the PlantUML feature is used, GenPackageDoc needs to know, where to find java. This is configured in the following way:

```
"JAVA" : {
          "WINDOWS" : "%JAVA_HOME%/bin/java.exe",
          "LINUX"   : "${JAVA_HOME}/bin/java"
         },
```
The problem is: On my Linux virtual machine the environment variable JAVA_HOME does not exist. I want to avoid to use hard coded paths to installations.

Is it possible that the installer checks the availability of java and creates this variable?

On my machine e.g. the value would currently be:

`JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64`

**Comment by test-fullautomation** [comment]
Hi Thong,
please look into this.
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Holger,
Cc Thomas,

As my investigation, we have a little different between platform Windows and OSD.
**Windows**
* Because the computer has already installed OpenJDK for JAVA before, so we don't need setting **JAVA_HOME**, and it still work correctly.


**OSD**
* By default, it don't install OpenJDK for JAVA, so we need to install it manually by command below
```bash
sudo apt-get install default-jdk
```
* Then it will generate the path at /usr/lib/jvm/java-11-openjdk-amd64
* Finally, we can set JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

To resolve this issues, I will request user to install OpenJDK when install our Robot Framework AIO, then I will add JAVA_HOME following the installed package OpenJDK.

If you have any comments, please tell me.

Thank you,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,

O.K. for Linux.

But for Windows you need to consider that we also don't know if we have the openjdk installed.
Only our Bosch-Internal Machines have this installed, but other machines from github users might not have.

Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

* About Linux, I have already updated code to implement it. Could you help me review code at branch:  [ htv3hc/feat/missing-variable-env](https://github.com/test-fullautomation/RobotFramework_AIO/tree/htv3hc/feat/missing-variable-env)
* About Windows, because I think there are some limitation when install package on windows, so I think that we only notify to user that if they want to use our software correctly, please install open-jdk manually. 
 For example about contents message notification.
```
  MsgPage4 := CreateOutputMsgPage(MsgPage2.ID,
             'Install dependency', 'How to use fully features on RobotFramework AIO',
             'You can easily generate documents with RobotFramework AIO (All In One) with the following steps:'#13#13+
             '  1. PlantUML: generate UML sequence.  '#13#13+
             'NOTE: Please manually install OpenJDK for Windows to use PlantUML correctly.');     
  
```
Then I will check that OpenJDK is already install on there local machine.
```
if not RegKeyExists(HKLM, 'SOFTWARE\JavaSoft\Java Development Kit') then
```
If not, I will open brower to download OpenJDK.
```
begin
    Answer := MsgBox('To use this software, you need to have OpenJDK installed.' +
                     ' Do you want to install it now?', mbConfirmation, MB_YESNO);
    if Answer = IDYES then
    begin
      // Open brower link to download openJDK
      ShellExec('open', 'https://openjdk.java.net/install/', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
      Result := False; // Stop user install Robot Framework AIO.
    end;
  end;
```
Could you think about it?

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,

thank you for your thougts.

PlantUML is a very small  side feature which we provide with genpackagedoc.
So we can't stop installation if the JDK is not available. It's not essential to be able to run or develop test cases.
It is even only required, if somebody wants to contribute to our repositories.

Therefore:
- as Holger requests: in Windows we try to set the JAVA_HOME variable, if a JDK is installed, but JAVA_HOME not set. This all must happen in a try/except block as it is not essential, but nice if it works.
- in Windows if JDK is not installed we ignore and proceed.

Thank you,
 Thomas
