### ISSUE TITLE
pull-request shall trigger build as pre-check for merging

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#137]
this applies for all repositories:
A new-pull-request, or updated-pull-request shall trigger a build as pre-check for merging.
It shall be executed immediately after new/updated pull-request.

A merge must not be done automatically.

**Comment by huavanthong** [comment]
Hi Thomas, 

I would like to confirm behavior for this ticket.
>  A new-pull-request, or updated-pull-request shall trigger a build as pre-check for merging.  

Currently, I have finished for this feature, the robotframework_aio repository is already triggered by new pull-request, or updated-pull-request.  
Regard to other repositories, when a new-pull-request, or updated-pull-request is created, it will trigger robotframework_aio repository build pipeline again. However, there are 2 ways to do it:  

* **Method 1:** I will immediately trigger the pipeline on robotframework_aio when a new-pull-request, or updated-pull-request of other repositories was merged to default branch.  

* **Method 2:** I will immediately trigger the pipeline on robotframework_aio when a new-pull-request, or updated-pull-request is created in other repositories. Then we will check the result of the pipeline on robotframework_aio, if it's OK, it will merge to default branch.

I think that method 1 is better than method 2 because the robotframework_aio of method 2 don't know the new branch of other repositories for trigger pipeline. Could you think about that?

Thank you and best regards.  
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,

Thank you for your thoughts:
I updated the description. "A merge must not be done automatically."
To avoid a misunderstanding. I want that the creator or updater of a pull-request (as well as me as merger) get's as early as possible feedback if the build works or not.
I would not merge in case of failure (except of the reason is minor).

Method 1: wrong from my point of view, because we don't merge. We talk about a pre-check as a condition for manual merge.

Method 2: sounds good as is what I want, but merge must be done manually by me.
Correct. You will have to consider the branches-to-use, because for the repository which triggers the build you must use the branch with the pull-request.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Shifted to 0.10.0

**Comment by huavanthong** [comment]
Hi Thomas,

I would like to update this ticket.
* Currently, I have created a job for listen event from other repositories at RobotFramework_AIO. 
More details refer: https://github.com/test-fullautomation/RobotFramework_AIO/pull/153

* About other repositories, I would like to update the workflow of other repositories for pull request. 
More details refer:  https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/228

If you have any comments, please tell me.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,
thank you for the update. 
I'll merge all related pull-requests as soon as we released our 0.9.0 version.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
As per comment from Ngoan that we will exceed the free 2.000 minutes for github actions we unfortunately can't do this, despite it would give a nice value.

@huavanthong : Decision: For the moment we let the feature only for the RobotFramework AIO repository, for all others we deactivate it. Please provide corresonding pull-requests.

**Comment by huavanthong** [comment]
Hi Thomas,

As my investigation, I have demonstrated that the public repositories will not charge the minutes when we trigger the build pipeline on Github Actions following [document](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions)

My demo following steps:
* I have changed the public repository to the private repository.
* I trigger the build pipeline on my repos.
* I can see that it will consume minutes in the Actions section.

Could you help me check if our repository has incurred any charged minutes in the past?
Link: https://github.com/settings/billing/summary
At Billing and plans -> Plans and usage -> Usage of month -> Actions
If there is no usage of minutes, I believe we don't need to be concerned about it in the future.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,

O.K. you motivated me to read again. I found that you are most likely right. It's really difficult to understand for me.
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
This page alss says that actions for public repositories are free.

=> I withdraw my comment from 3h ago.
     We rollout the pre-check for all repositories and look what happens to our minutes. Most likely they will remain 0. 
     test-fullautomation account has 0 Minutes use of actions up to now.
     Please provide pull-requests for all repositories.

Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

This issue was resolved. Please help me close this ticket.

Thank you,
Thong Hua

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
