### ISSUE TITLE
linux version number in controlfile must be part of automation

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#158]
a `dev` or `rel` tag must set the linux version provided in the control file properly.

preferred would be hat the deb build get's the version number a argument.
Possible, but not nice would be to manipulate the control file before build.

**Comment by huavanthong** [comment]
Hi Thomas,

As I known that we've already updated the linux version number in controlfile in ticket https://github.com/test-fullautomation/RobotFramework_AIO/issues/118.  
However, it only updated on local machine and it can't update into the source code lead to the Gitlab repos can't receive the exact version for installing tool.

**Solution**
* To resolve this issue, I will create the necessary steps for automating commit the changes on local machine and generating a merge request automatically, allowing you to merge it 

How do you think about it?

Thank you, 
Thong Hua

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
actually I'm confused now.
I checked both, latest dev/0.9.0.1 build with Gitlab and Githab. Both have correct version information for Linux and Windows.
@HolQue : You had a finding that the built files don't have correct version information. Where did you find this. Already merged #146 should solve this problem. für dev/0.9.0.1 I could not find consistencies.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi @test-fullautomation,

Installer `RobotFramework_AIO_setup_merged_develop.exe` taken from:

https://gitlab-apertispro.boschdevcloud.com/robotframework-aio/main/robotframework_aio/-/jobs/2808578/artifacts/download

**Comment by test-fullautomation** [comment]
Hi @HolQue ,

O.K. then I understand the problem. Here I didn't provide a release tag.
Solution could be that I use from now onwards always the `dev`  tag, when we start testing release candidates.

@huavanthong : please check also automating commiting an ujpdated control file. This will not solve Holgers problem, but it creates more consistency in our repositories.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi all,

The Holger's observation is correct!
Currently, the version information is only taken from `dev` and `rev` in case the pipeline is triggered by `dev` or `rel`.

Otherwise, there is no information about the version (except `control` file, it is also not up-to-date), so I used the trigger event (merge_develop or dev branch) as version information for Windows installer.
So that, for the daily build and merged PR build will not have the proper version info that we expected (such as 0.9.0)

I wonder that do we need to maintain version information (in files such as `control` file) so that all the stuff with related to version will refer to that file?

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
@ngoan1608 : from my point nothing to do. I will take care that I create releases based on ```dev``` tags when I request testing.

Hm... but you are right, there is one disadvantage: the daily builds will be inconsistent...

**Comment by ngoan1608** [comment]
Hi Thomas,

I think the job to commit an updated version in `control` file (when building with t`dev/rel` tag) will help to maintain the version information.
But, I concern that it is not a good idea to commit and push change directly yo `develop` branch for updated `control` file.
Besides, the commit for update version of `control` will be ahead of `dev/rel` tag if we do it in build pipeline.

Thank you,
Ngoan

**Comment by huavanthong** [comment]
Hi Thomas,
Cc Ngoan

I would like to make clear this issue on GitLab.
* Currently, we can build correctly Tool version on Gitlab by define tag = 0.9.0.1. However, because the [control file](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/config/build/dpkg_build/control) specific the version for Tool is 0.8.x.x.  
==> On OSD platform will need downgrade from version 0.9.0.1 to 0.8.x.x 
* On Gitlab source code, it will mirror the source code from RobotFramework_AIO Github, and because we don't update control file manually lead to it can't know the version info correctly.  

As your suggestion, we need to automate this behavior, so my solution will create a commit on the changes of version in control file, and create a merge request automatically => Then you only merge it for correcting the version info. 
 
For an example of workflow: 
* Trigger tag job -> Build AIO job -> Test AIO job ->  Automate the control file update job.

Operation of Automate the control file update job:
* Create a new branch based on tag info -> Update control file -> Commit -> Push on the new branch -> Create a pull request.

**Conclusion**
With this solution, you will be able to merge it and correct the information in the control file after triggering the tag job.

That's all for my info. If you have any concerns,  please let me know.

Thank you,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,

"Create a new branch based on tag info -> Update control file -> Commit -> Push on the new branch -> Create a pull request."
is a good idea.
We try it this way. Please provide a pull-request for this.

Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

This issue was resolved. Please help me close this ticket.

Thank you,
Thong Hua

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
