### ISSUE TITLE
VSCodium: Key binding for Python script execution wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#225]
Robot files opened in VSCodium editor, can be executed by **CTRL+F5**. This activates the Run button, that is preconfigured in a certain way.

The corresponding function for the execution of Python scripts is "`Run Python File in Terminal`". But this function is not assigned to any key combination yet.

To support the automated test execution under VSCodium I would like to have such a key combination preconfigured.

Maybe something nearby **CTRL+F5**, e.g. **CTRL+F6** (in case of this is not yet assigned to any other function).

**Comment by huavanthong** [comment]
Hi Holger,

I have checked your suggestion. 
Because there are no any function for **CTRL+F6** key, so I have bound the execution of Python scripts is "Run Python File in Terminal" into it.

Please take it for your info, if you have any concerns, please tell me.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
already merged for 0.11.0
