### ISSUE TITLE
plantuml plugin for VS Codium

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#80]
1. VS Codium shall have plantuml plugin preinstalled.

2. To support GenpackageDoc the build process shall provide:

   `set RobotPlantUMLPath=%ROBOTVSCODE%/data/extensions/jebbs.plantuml-2.17.5-universal`

   Because of we have a dependency to java now (when calling plantuml.jar in command line - outside VS Codium), I suggest to 
   let the build process check the current java version.

Both is required that https://github.com/test-fullautomation/python-genpackagedoc/pull/51 works properly.

Addendum by HolQue:

The name of the environment variable is "`GENDOC_PLANTUML_PATH`" now (because belongs to `GenPackageDoc`, and not to Robot Framework immediately).

**Comment by HolQue** [comment]
To support `GenpackageDoc` I ask the build process to provide:

`set RobotPlantUMLPath=%ROBOTVSCODE%/data/extensions/jebbs.plantuml-2.17.5-universal`

Because of we have a dependency to java now (when calling `plantuml.jar` in command line - outside VS Codium), I suggest to let the build process check the current java version.

**Comment by test-fullautomation** [comment]
Hi Nguyen,
can you please give me a status for this.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
solved and merged with #91
